name: ðŸŸ¢ Start Parkalot

# run daily at 10:58 UTC â†’ 11:58 BST
on:
  schedule:
    - cron: '29 19 * * *'

jobs:
  start-container:
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set default resource group
        run: az configure --defaults group=parkalot-rg

      - name: Start container
        run: |
          az container create \
            --name parkalot-cron \
            --image parkalotacr7620.azurecr.io/parkalot:latest \
            --registry-login-server parkalotacr7620.azurecr.io \
            --registry-username ${{ secrets.ACR_USER }} \
            --registry-password ${{ secrets.ACR_PASS }} \
            --cpu 0.5 --memory 1 \
            --os-type Linux \
            --restart-policy OnFailure \
            --environment-variables \
              PARKALOT_USER=${{ secrets.PARKALOT_USER }} \
              PARKALOT_PASS=${{ secrets.PARKALOT_PASS }}
